services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${SPRING_RABBITMQ_HOST}
    ports:
      - 5672:5672
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${SPRING_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${SPRING_RABBITMQ_PASSWORD}
    networks:
      - api-network
    restart: always

  api:
    image: ezequaiss/admonteiro:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
    networks:
      - api-network
    restart: always

networks:
  api-network:
    driver: bridge